# Conflicts with RSpec `let (:var) { value }` form
Lint/ParenthesesAsGroupedExpression: {Enabled: false}

Metrics/BlockLength: {Enabled: false}
Metrics/LineLength: {Max: 125}

Style/MultilineIfThen: {Enabled: false}
